name: Publish
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - uses: actions/setup-node@v4
      with:
        always-auth: true
        registry-url: https://registry.npmjs.org/

    - name: Publish to npm
      run: yarn publish --access public
      continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - uses: actions/setup-node@v4
      with:
        registry-url: https://npm.pkg.github.com

    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}